name: Check

on:
  workflow_dispatch: # can be triggered manually
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches-ignore:
      - update/*
    paths-ignore:
      - "LICENSE"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v31
      - name: Generate Nix Matrix
        id: set-matrix
        run: |
          set -Eeu
          matrix=$(nix eval --json .#githubActions.matrix)
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  build:
    uses: ./.github/workflows/build.yml
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    secrets: inherit
    with:
      name: ${{ matrix.name }}
      builds: ${{ toJSON(matrix.builds) }}
